---
title: "R Notebook"
output:
  html_document: 
    keep_md: yes
    toc: yes
    toc_float: true
    collapsed: false
    theme: spacelab
    number_sections: yes
    df_print: tibble
    highlight: zenburn
    fig_width: 10
    fig_height: 10
  word_document: default
  md_document:
    variant: markdown_github
  pdf_document: default
---


```{r setup, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(cache = F, message=FALSE, warning=FALSE)
```


##Segementation test
The identification summary.
```{r eval=FALSE, include=FALSE}
library(HiTMaP)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_1seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=1,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_2seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=2,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_3seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=3,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_4seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=4,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_5seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=5,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_6seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=6,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_7seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=7,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_8seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=8,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_9seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=9,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_10seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=10,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_11seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=11,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_12seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=12,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_13seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=13,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_14seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=14,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_15seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=15,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_16seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=16,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01)

imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_1seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=1,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_2seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=2,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_3seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=3,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_4seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=4,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_5seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=5,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_6seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=6,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_7seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=7,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_8seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=8,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_9seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=9,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_10seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=10,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_11seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=11,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_12seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=12,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_13seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=13,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_14seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=14,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_15seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=15,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_16seg/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=16,use_previous_candidates=T,threshold=0.005,FDR_cutoff=0.01,peptide_ID_filter=3)


```

```{r eval=T, message=FALSE, warning=FALSE, include=T}
library(dplyr)
library(readr)
  Protein_Summary<-list()
totalseg<-16
for (Segmentation_number in 1:totalseg){
  Protein_Summary[[Segmentation_number]] <- read_csv(paste0("D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_",Segmentation_number,"seg/Summary folder/Protein_peptide_Summary.csv"))
  Protein_Summary[[Segmentation_number]]$Segmentation_number=Segmentation_number
  }
  
  Protein_Summary_bind<-do.call(rbind,Protein_Summary)
  Protein_Summary_bind_protein<-Protein_Summary_bind %>% group_by(Segmentation_number) %>% summarise(Protein_num=length(unique(Protein)))
  Protein_Summary_bind_peptide<-Protein_Summary_bind %>% group_by(Segmentation_number) %>% summarise(Peptide_num=length(unique(Peptide)))
  Protein_Summary_bind_Score<-Protein_Summary_bind %>% group_by(.dots=c("Segmentation_number","Peptide")) %>% summarise(Peptide_Score=(max(Score)))
  
  
  common_pep<-Protein_Summary_bind_Score[,c("Segmentation_number","Peptide")] %>% 
  group_by(Peptide) %>% mutate(In_groups = length(unique(Segmentation_number))) %>% 
  ungroup() %>% filter(In_groups == length(unique(Segmentation_number))) %>%  .$Peptide %>% 
  unique()
  
  Protein_Summary_bind_Score_common_mean<-Protein_Summary_bind_Score[Protein_Summary_bind_Score$Peptide %in% common_pep,]  %>% group_by(.dots=c("Segmentation_number")) %>% summarise(Peptide_Score=(mean(Peptide_Score)))
  
```

Protein NR count vs. sementation number
```{r eval=T, message=FALSE, warning=FALSE, include=T}
  plot(Protein_Summary_bind_protein)

```

Peptide NR count vs. sementation number
```{r eval=T, message=FALSE, warning=FALSE, include=T}
  plot(Protein_Summary_bind_peptide)
```

Peptide score(regions' median) vs. sementation number
```{r eval=T, message=FALSE, warning=FALSE, include=T}
plot(Protein_Summary_bind_Score_common_mean)

```



The spectrum quality summary:

```{r eval=T, message=FALSE, warning=FALSE, include=T}
library(dplyr)
library(readr)
library(ggplot2)
library(FTICRMS)
library(Cardinal)
  Protein_Summary_bind_Delta_ppm<-Protein_Summary_bind[Protein_Summary_bind$Peptide %in% common_pep,] %>% group_by(.dots=c("Segmentation_number","Peptide")) %>% summarise(Delta_ppm=(min(Delta_ppm)))
  Protein_Summary_bind_Delta_ppm_min<-Protein_Summary_bind_Delta_ppm %>% group_by(.dots=c("Segmentation_number")) %>% summarise(Delta_ppm=(mean(Delta_ppm)))
 
  plot(Protein_Summary_bind_Delta_ppm_min)
  
  spectrum<-list()
  for (Segmentation_number in 1:totalseg){
    spectrum[[Segmentation_number]]<-list()
    for (seg in 1:Segmentation_number){
      spectrum[[Segmentation_number]][[seg]]<- read_csv(paste0("D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_",Segmentation_number,"seg/Bovin_lens ID/",seg,"/Spectrum.csv"))
      spectrum[[Segmentation_number]][[seg]]$seg<-seg
      spectrum[[Segmentation_number]][[seg]]$Segmentation_number=Segmentation_number
    }

  }
  
  
  
  spectrum_bind<-do.call(rbind,spectrum)
  spectrum_bind_bind<-do.call(rbind,spectrum_bind)
  spectrum_bind_bind<-unique(spectrum_bind_bind)
  imdata<-Cardinal::readMSIData("D:/GITHUB LFS/HiTMaP-Data/inst/segmentation test/Bovinlens_Trypsin_FT_1seg/Bovin_lens.imzML",resolution=5)
  mz.all.df<-data.frame(m.z=imdata@featureData@mz)
  mz.all.df$mz_start<-mz.all.df$m.z
  mz.all.df$mz_end<-c(mz.all.df$m.z[2:length(mz.all.df$m.z)],mz.all.df$m.z[length(mz.all.df$m.z)]*2-mz.all.df$m.z[length(mz.all.df$m.z)-1])
  mz.all.df$m.z<-NULL
  #abs(diff(mz.all.df$m.z))
  
  #mz.all.df<-summarize(imdata, .stat="mean", .by="feature", .as="DataFrame")
  
  #sum((spectrum[[2]][[1]]$m.z %in% mz.all.df$m.z))
  #which.min(abs(diff(spectrum[[2]][[1]]$m.z)))
  spectrum_bind_bind<-spectrum_bind_bind[order(spectrum_bind_bind$Segmentation_number,spectrum_bind_bind$seg,spectrum_bind_bind$m.z),]
  
  
  
  
  spectrum_bind_bind_rank<-spectrum_bind_bind %>% group_by(.dots=c("Segmentation_number","seg"))  %>% summarise(min=min(intensities),median=median(intensities))
  spectrum_bind_bind_rank
  ggplot(spectrum_bind_bind_rank,aes(x=interaction(seg,Segmentation_number),y=min)) +
  geom_bar(stat="identity")
  ggplot(spectrum_bind_bind_rank,aes(x=interaction(seg,Segmentation_number),y=median)) +
  geom_bar(stat="identity")
  min(spectrum_bind_bind$intensities)
  max(spectrum_bind_bind$intensities)
  
  impute_bin_spec_fun<-function(spectrum_bind_bind,Segmentation_number,mz.all.df){
    
    library(tidyverse)
    library(fuzzyjoin)
    library(data.table)
    library(lubridate )
    library(sqldf)
    mz.all.df<-as.data.table(mz.all.df)
    
    locate.peaks_spec<-NULL
    for (seg in 1:Segmentation_number){    spectrum_bind_bind_log<-spectrum_bind_bind['&'(spectrum_bind_bind$Segmentation_number==Segmentation_number,spectrum_bind_bind$seg==seg),1:2]
    spectrum_bind_bind_log<-as.data.table(spectrum_bind_bind_log)
    mzdf<-mz.all.df
    spectrum_bind_bind_log$mz<-spectrum_bind_bind_log$m.z
    output <- sqldf('SELECT spectrum_bind_bind_log.mz, spectrum_bind_bind_log.intensities , mzdf.mz_start 
      FROM spectrum_bind_bind_log 
      LEFT JOIN mzdf ON mz BETWEEN mz_start and mz_end')
    output_merge<-merge(mzdf,output,by="mz_start",all.x = T)
    sum(output_merge$mz_start %in% mzdf$mz_start)
    output_merge$mz<-output_merge$mz_start
    output_merge[is.na(output_merge)]<-0
    output_merge$Segmentation_number=Segmentation_number
    output_merge$seg=seg
    locate.peaks_spec<-rbind(locate.peaks_spec,output_merge[,c("mz","intensities","Segmentation_number","seg")])
  }

  return(locate.peaks_spec)
  }
  spectrum_bind_bind_impute<-spectrum_bind_bind
  #spectrum_bind_bind_impute<-NULL
  #for  (Segmentation_number in 1:totalseg){
  #spectrum_bind_bind_impute<-rbind(spectrum_bind_bind_impute,impute_bin_spec_fun(spectrum_bind_bind,Segmentation_number,mz.all.df))
  #}
  
  locate.peaks_spec_fun<-function(spectrum_bind_bind,Segmentation_number){
    locate.peaks_spec<-list()
    for (seg in 1:Segmentation_number){    spectrum_bind_bind_log<-spectrum_bind_bind['&'(spectrum_bind_bind$Segmentation_number==Segmentation_number,spectrum_bind_bind$seg==seg),1:2]
  spectrum_bind_bind_log<-as.matrix(spectrum_bind_bind_log)
  locate.peaks_spec[[seg]]<-locate.peaks(spectrum_bind_bind_log,num.pts = 5,thresh = max(spectrum_bind_bind[,2])*0.001)
  message(max(spectrum_bind_bind[,2])*0.001)
  }

  locate.peaks_spec
  }
  locate.peaks_spec_bindlist<-list()
  for  (Segmentation_number in 1:totalseg){
  locate.peaks_spec<-locate.peaks_spec_fun(spectrum_bind_bind_impute,Segmentation_number)
  locate.peaks_spec_bind<-do.call(rbind,locate.peaks_spec)
  locate.peaks_spec_bind<-locate.peaks_spec_bind[!duplicated(locate.peaks_spec_bind$Center_hat),]
  locate.peaks_spec_bindlist[[Segmentation_number]]<-locate.peaks_spec_bind
  
  }
  
  locate.peaks_spec_bindlist_merge<-list()
  for  (Segmentation_number in 1:totalseg){

  locate.peaks_spec_bindlist[[Segmentation_number]]$Segmentation_number<-Segmentation_number
  #locate.peaks_spec_bindlist[[Segmentation_number]]$Center_hat<-round(locate.peaks_spec_bindlist[[Segmentation_number]]$Center_hat,digits = 3)
  }
```


```{r eval=T, message=FALSE, warning=FALSE, include=T}
  locate.peaks_spec_bindlist_bind <- do.call(rbind,locate.peaks_spec_bindlist,quote = F)
  locate.peaks_spec_bindlist_bind$Segmentation_number<-as.factor(locate.peaks_spec_bindlist_bind$Segmentation_number)
  locate.peaks_spec_bindlist_bind$Width_hat_log<-log(locate.peaks_spec_bindlist_bind$Width_hat)
  g<-ggplot(locate.peaks_spec_bindlist_bind,aes(x=Max_hat,y=Width_hat,col=Segmentation_number))+geom_point()
  
  
  g
  
  
  
  common_feature<-locate.peaks_spec_bindlist_bind %>% group_by(round(Center_hat,digits = 3)) %>% summarise(count=length(Width_hat))
  common_feature<-common_feature[common_feature$count>=0.15*totalseg,]
  
  locate.peaks_spec_bindlist_bind$Center_hat<-round(locate.peaks_spec_bindlist_bind$Center_hat,digits = 2)
  common_feature<-locate.peaks_spec_bindlist_bind %>% 
  group_by(Center_hat) %>% mutate(In_groups = length(unique(Segmentation_number))) %>% 
  ungroup() %>% filter(In_groups >= 5) %>%  .$Center_hat %>% 
  unique()
  
  
  locate.peaks_spec_bindlist_bind_filtered<-locate.peaks_spec_bindlist_bind[locate.peaks_spec_bindlist_bind$Center_hat %in% common_feature,]
  
  unfiltered_width<-locate.peaks_spec_bindlist_bind %>% group_by(Segmentation_number) %>% summarise(width=median(Width_hat))
  filtered_width<-locate.peaks_spec_bindlist_bind_filtered %>% group_by(Segmentation_number) %>% summarise(width=median(Width_hat))
  plot(unfiltered_width, type="l")
  plot(filtered_width,type="l")
  lines(filtered_width,type = "l", lty = 1)
```


```{r eval=T, message=FALSE, warning=FALSE, include=T}
peak_num<-unlist(lapply(locate.peaks_spec_bindlist,nrow))
  peak_width<-unlist(lapply(locate.peaks_spec_bindlist,function(x){max(x$Width_hat)}))
  #ggplot(NULL,aes(x=peak_num,y=peak_width)) +  geom_bar(stat="identity")


```



##Enzyme test
```{r eval=F}
enzyme<-c("trypsin","lysn","lysc","caspase1","asp-n endopeptidase","pepsin","proteinase k")
for (i in 1:length(enzyme)){
imaging_identification(datafile=paste0("D:/GITHUB LFS/HiTMaP-Data/inst/Enzyme test/Bovinlens_Trypsin_FT ",enzyme[i],"/Bovin_lens.imzML"),Digestion_site=enzyme[i],Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=T,spectra_segments_per_file=4,use_previous_candidates=F,peptide_ID_filter=3,threshold = 0.005,FDR_cutoff=0.01)
}
```


```{r}
library(dplyr)
library(ggplot2)
enzyme<-c("trypsin","lysn","lysc","caspase1","asp-n endopeptidase","pepsin","proteinase k")
enzyme<-c("trypsin","lysn","lysc","caspase1","asp-n endopeptidase")
Protein_Summary<-list()
for (indx in 1:length(enzyme)){
  Protein_Summary[[enzyme[indx]]] <- readr::read_csv(paste0("D:/GITHUB LFS/HiTMaP-Data/inst/Enzyme test/Bovinlens_Trypsin_FT ",enzyme[indx],"/Summary folder/Protein_peptide_Summary.csv"))
  #Protein_Summary[[enzyme[indx]]]$indx=enzyme[indx]
}
candidatelist<-NULL
for (indx in 1:length(enzyme)){
  candidatelist[[enzyme[indx]]] <- readr::read_csv(paste0("D:/GITHUB LFS/HiTMaP-Data/inst/Enzyme test/Bovinlens_Trypsin_FT ",enzyme[indx],"/Summary folder/candidatelist.csv"))
  #Protein_Summary[[enzyme[indx]]]$indx=enzyme[indx]
}
  #Protein_Summary <-tidyr::hoist(Protein_Summary)
  #Protein_Summary <-  mapply(`[<-`, Protein_Summary, 'Species', value = names(Protein_Summary), SIMPLIFY = FALSE)
  Protein_Summary_bind<-do.call(rbind,Protein_Summary)
  Protein_Summary_bind$indx<-rep(enzyme,lapply(Protein_Summary,nrow))
  Protein_Summary_bind_proteinnr<-unique(Protein_Summary_bind[,c("Protein","indx")])
  Protein_Summary_bind_peptidenr<-unique(Protein_Summary_bind[,c("Peptide","indx")])
  Protein_Summary_bind_protein<-Protein_Summary_bind %>% group_by(indx) %>% summarise(Protein=length(unique(Protein)))
  #Protein_Summary_bind_peptide<-Protein_Summary_bind %>% group_by(indx) %>% summarise(Peptide=(unique(Peptide)))
  #Protein_Summary_bind_Score<-Protein_Summary_bind %>% group_by(.dots=c("indx","Peptide")) %>% summarise(Peptide_Score=(max(Score)))
  #Protein_Summary_bind_Score_max<-Protein_Summary_bind_Score %>% group_by(.dots=c("indx")) %>% summarise(Peptide_Score=(mean(Peptide_Score)))
  #ggplot(Protein_Summary_bind_protein, aes(x=indx,y=Protein,group=indx)) + geom_bar(position="dodge", stat="identity")
  ggplot(Protein_Summary_bind_proteinnr, aes(x=indx,group=indx)) + geom_bar(position="dodge", stat="Count")
  ggplot(Protein_Summary_bind_peptidenr, aes(x=indx,group=indx)) + geom_bar(position="dodge", stat="Count")
  candidate_number<-lapply(candidatelist,nrow)
 
```



##FDR test

```{r eval=F}
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/FDR test/Bovinlens_Trypsin_FT fdr01/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=4,use_previous_candidates=T,peptide_ID_filter=3,threshold = 0.005,FDR_cutoff=0.01)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/FDR test/Bovinlens_Trypsin_FT fdr05/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=4,use_previous_candidates=T,peptide_ID_filter=3,threshold = 0.005,FDR_cutoff=0.05)
imaging_identification(datafile="D:/GITHUB LFS/HiTMaP-Data/inst/FDR test/Bovinlens_Trypsin_FT fdr10/Bovin_lens.imzML",Digestion_site="trypsin",Fastadatabase="uniprot-Bovin.fasta",output_candidatelist=F,spectra_segments_per_file=4,use_previous_candidates=T,peptide_ID_filter=3,threshold = 0.005,FDR_cutoff=0.10)

```


```{r}
library(dplyr)
library(ggplot2)
fdr<-c("01","05","10")
Protein_Summary<-list()
for (indx in 1:length(fdr)){
  Protein_Summary[[fdr[indx]]] <- readr::read_csv(paste0("D:/GITHUB LFS/HiTMaP-Data/inst/FDR test/Bovinlens_Trypsin_FT fdr",fdr[indx],"/Summary folder/Protein_peptide_Summary.csv"))
  #Protein_Summary[[fdr[indx]]]$indx=fdr[indx]
}

  #Protein_Summary <-tidyr::hoist(Protein_Summary)
  #Protein_Summary <-  mapply(`[<-`, Protein_Summary, 'Species', value = names(Protein_Summary), SIMPLIFY = FALSE)
  Protein_Summary_bind<-do.call(rbind,Protein_Summary)
  Protein_Summary_bind$indx<-rep(fdr,lapply(Protein_Summary,nrow))
  Protein_Summary_bind_proteinnr<-unique(Protein_Summary_bind[,c("Protein","indx")])
  Protein_Summary_bind_peptidenr<-unique(Protein_Summary_bind[,c("Peptide","indx")])
  Protein_Summary_bind_protein<-Protein_Summary_bind %>% group_by(indx) %>% summarise(Protein=length(unique(Protein)))
  #Protein_Summary_bind_peptide<-Protein_Summary_bind %>% group_by(indx) %>% summarise(Peptide=(unique(Peptide)))
  #Protein_Summary_bind_Score<-Protein_Summary_bind %>% group_by(.dots=c("indx","Peptide")) %>% summarise(Peptide_Score=(max(Score)))
  #Protein_Summary_bind_Score_max<-Protein_Summary_bind_Score %>% group_by(.dots=c("indx")) %>% summarise(Peptide_Score=(mean(Peptide_Score)))
  #ggplot(Protein_Summary_bind_protein, aes(x=indx,y=Protein,group=indx)) + geom_bar(position="dodge", stat="identity")
  ggplot(Protein_Summary_bind_proteinnr, aes(x=indx,group=indx)) + geom_bar(position="dodge", stat="Count")
  ggplot(Protein_Summary_bind_peptidenr, aes(x=indx,group=indx)) + geom_bar(position="dodge", stat="Count")

 
```


