FROM mashuoa/hitmap:latest


LABEL org.opencontainers.image.licenses="GPL-3.0-or-later" \
      org.opencontainers.image.source="https://github.com/MASHUOA/hitmap_docker" \
      org.opencontainers.image.vendor="HiTMaP Docker Project" \
      org.opencontainers.image.authors="George Guo <george.guo@auckland.ac.nz>"

WORKDIR /build

COPY . .

# Install system dependencies and clean up afterwards

RUN Rscript install.R

#RUN R CMD javareconf
CMD ["/bin/bash"]
ENTRYPOINT ["/bin/sh","-c"]