FROM rocker/rstudio


LABEL org.opencontainers.image.licenses="GPL-3.0-or-later" \
      org.opencontainers.image.source="https://github.com/MASHUOA/hitmap_docker" \
      org.opencontainers.image.vendor="HiTMaP Docker Project" \
      org.opencontainers.image.authors="George Guo <george.guo@auckland.ac.nz>"

WORKDIR /build

COPY . .

# Install system dependencies and clean up afterwards

RUN apt-get update \
 && apt-get upgrade -y 

RUN apt-get install -y dialog
RUN apt-get install -y default-jdk
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y libxml2-dev
RUN apt-get install -y libssl-dev
RUN apt-get install -y libudunits2-dev
RUN apt-get install -y librsvg2-dev
RUN apt-get install -y libmagick++-dev
RUN apt-get install -y r-cran-ncdf4
RUN apt-get install -y libz-dev
RUN apt-get install -y libnss-winbind
RUN apt-get install -y winbind
RUN apt-get install -y dirmngr
RUN apt-get install -y gnupg
RUN apt-get install -y apt-transport-https
RUN apt-get install -y ca-certificates
RUN apt-get install -y software-properties-common
RUN apt-get install -y libfftw3-dev
RUN apt-get install -y texlive
RUN apt-get install -y libgdal-dev
RUN apt-get install -y ghostscript
RUN apt-get install -y libharfbuzz-dev
RUN apt-get install -y libfribidi-dev
RUN rm -rf /var/lib/apt/lists/*
# Replace configuration file for Image Magick
COPY ./policy.xml /etc/ImageMagick-6

RUN Rscript install.R

RUN R CMD javareconf
CMD ["/bin/bash"]
ENTRYPOINT ["/bin/sh","-c"]