FROM rocker/r-base:4.4.1


LABEL org.opencontainers.image.licenses="GPL-3.0-or-later" \
      org.opencontainers.image.source="https://github.com/MASHUOA/hitmap_docker" \
      org.opencontainers.image.vendor="HiTMaP Docker Project" \
      org.opencontainers.image.authors="George Guo <george.guo@auckland.ac.nz>"

WORKDIR /build
#RUN whoami
#RUN id
#RUN usermod -a -G sudo root
#RUN gpasswd -d root nogroup
#RUN su - root
#RUN id
#RUN apt-get update
#RUN usermod --add-subuids 100000-200000 --add-subgids 100000-200000 root
#RUN apt-get autoremove && apt-get clean && apt-get autoclean
#RUN chmod -Rv 700 /var/cache/apt/archives/partial/
#RUN chmod -R a=u,go-w /var/cache/apt/*

#COPY sandbox-disable /etc/apt/apt.conf.d/sandbox-disable

COPY . .

# Install system dependencies and clean up afterwards

RUN apt-get update \
 && apt-get upgrade -y 
RUN apt-get install -y aptitude
RUN aptitude install -y dialog default-jdk libcurl4-openssl-dev libxml2-dev libssl-dev libudunits2-dev
RUN aptitude install -y librsvg2-dev libmagick++-dev r-cran-ncdf4 libz-dev libnss-winbind
RUN aptitude install -y winbind dirmngr gnupg apt-transport-https ca-certificates software-properties-common 
RUN aptitude install -y libfftw3-dev texlive libgdal-dev ghostscript libharfbuzz-dev libfribidi-dev
RUN rm -rf /var/lib/apt/lists/*

COPY install_step2.R /install_step2.R
RUN Rscript /install_step2.R

# Replace configuration file for Image Magick
COPY ./policy.xml /etc/ImageMagick-6

RUN Rscript install.R

RUN R CMD javareconf
CMD ["/bin/bash"]
