FROM rocker/r-ver:latest

LABEL org.opencontainers.image.licenses="GPL-2.0-or-later" \
      org.opencontainers.image.source="https://github.com/rocker-org/rocker-versioned2" \
      org.opencontainers.image.vendor="Rocker Project" \
      org.opencontainers.image.authors="Carl Boettiger <cboettig@ropensci.org>"

ENV S6_VERSION=v2.1.0.2
ENV SHINY_SERVER_VERSION=latest
ENV PANDOC_VERSION=default

COPY install_step1.R /rocker_scripts/bin/install_step1.R
COPY install_step2.R /rocker_scripts/bin/install_step2.R
COPY install_shiny_deps.R /rocker_scripts/bin/install_shiny_deps.R
COPY hitmap_shiny_server.sh /rocker_scripts/hitmap_shiny_server.sh
COPY hitmap_shiny_server2.sh /rocker_scripts/hitmap_shiny_server2.sh

RUN /rocker_scripts/hitmap_shiny_server.sh
RUN Rscript /rocker_scripts/bin/install_step1.R
RUN Rscript /rocker_scripts/bin/install_step2.R
RUN Rscript /rocker_scripts/bin/install_shiny_deps.R
RUN R CMD javareconf
RUN /rocker_scripts/hitmap_shiny_server2.sh

COPY ./policy.xml /etc/ImageMagick-6


CMD ["/init"]
EXPOSE 3838
