#install the git package
install.packages("BiocManager")
install.packages("remotes")
install.packages("config")
install.packages("textshaping")
install.packages("ragg")
install.packages("pkgdown")
install.packages("devtools")
install.packages("shinyjs")
install.packages("promises")
install.packages("future")
install.packages("magrittr")
install.packages("shinyFiles")
if (!require(plotly)) devtools::install_github("ropensci/plotly@async")
if (!require(htmlwidgets)) devtools::install_github("ramnathv/htmlwidgets")
install.packages("shinythemes")
install.packages("tidyverse")
install.packages("shinyjs")
install.packages("reshape2")
