FROM mashuoa/hitmap:base

LABEL org.label-schema.license="GPL-3.0" \
      org.label-schema.vcs-url="https://github.com/MASHUOA/HiTMaP" \
      org.label-schema.vendor="MASHUOA/HiTMaP" \
      maintainer="George GUO <George.guo@auckland.ac.nz>"

ENV S6_VERSION=v1.21.7.0
ENV SHINY_SERVER_VERSION=latest
ENV PANDOC_VERSION=default
ENV HITMAP_VERSION=latest

EXPOSE 3838

EXPOSE 8787

RUN sudo apt-get install tcl-dev tk-dev
RUN sudo apt-get install r-cran-ncdf4
RUN sudo apt-get install libz-dev
RUN sudo apt install libxml2-dev
RUN sudo apt install libssl-dev
RUN sudo apt install libcurl4-openssl-dev
RUN sudo apt-get install libnss-winbind winbind
RUN sudo apt install dirmngr gnupg apt-transport-https ca-certificates software-properties-common

RUN sudo add-apt-repository ppa:webupd8team/y-ppa-manager
RUN sudo apt-get update
RUN sudo apt-get install y-ppa-manager
RUN sudo y-ppa-manager

RUN sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys
RUN sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
RUN sudo apt-cache policy r-base
RUN sudo apt-get purge r-base
RUN sudo apt-get install r-base-core="4.0.2-1.2004.0"
RUN sudo apt-get install libmagick++-dev

RUN sudo apt-get install libfftw3-dev
RUN sudo apt-get install r-base-dev texlive-full
RUN sudo apt-get install libudunits2-dev
RUN sudo apt-get install libgdal-dev

RUN unset R_HOME



CMD ["/init"]
