FROM rocker/r-ver:4.0.3

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"

ENV S6_VERSION=v1.21.7.0
ENV SHINY_SERVER_VERSION=latest
ENV PANDOC_VERSION=default
ENV HITMAP_VERSION=latest

RUN /HiTMaP_scripts/install_HiTMaP.sh

EXPOSE 3838

CMD ["/init"]
