FROM rocker/r-ver:4.0.2

LABEL org.label-schema.license="GPL-3.0" \
      org.label-schema.vcs-url="https://github.com/MASHUOA/HiTMaP" \
      org.label-schema.vendor="MASHUOA/HiTMaP" \
      maintainer="George GUO <George.guo@auckland.ac.nz>"

ENV S6_VERSION=v1.21.7.0
ENV SHINY_SERVER_VERSION=latest
ENV PANDOC_VERSION=default
ENV HITMAP_VERSION=latest

RUN /HiTMaP_scripts/install_HiTMaP.sh

EXPOSE 3838

CMD ["/init"]
