FROM mashuoa/hitmap:base_prep


LABEL org.opencontainers.image.licenses="GPL-3.0-or-later" \
      org.opencontainers.image.source="https://github.com/MASHUOA/hitmap_docker" \
      org.opencontainers.image.vendor="HiTMaP Docker Project" \
      org.opencontainers.image.authors="George Guo <george.guo@auckland.ac.nz>"

WORKDIR /build

COPY hitmap_base.sh /hitmap_base.sh
COPY install.R /install.R
COPY install_step2.R /install_step2.R
RUN Rscript /install_step2.R

# Replace configuration file for Image Magick
COPY ./policy.xml /etc/ImageMagick-6


RUN R CMD javareconf
CMD ["/bin/bash"]
